# Generated by Django 6.0.1 on 2026-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_address_alter_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.AddField(
            model_name='budget',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='income',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_status',
            field=models.TextField(blank=True, choices=[('1', 'Employed Full-time'), ('2', 'Employed Part-time'), ('3', 'Unemployed'), ('4', 'Retired'), ('5', 'Student')], null=True),
        ),
    ]
