# Generated by Django 5.0.7 on 2026-01-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_goal_status_budget_active_goal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
