# Generated by Django 5.0.7 on 2026-01-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='is_active',
        ),
    ]
