# Generated by Django 5.0.7 on 2026-01-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account_income_account_transaction_account_and_more'),
        ('core', '0006_notification'),
    ]

    operations = [
    ]
