# Generated by Django 5.0.7 on 2026-01-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260119_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type_spending',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='store_name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.TextField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], default='EXPENSE'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.budget'),
        ),
    ]
