# Generated by Django 5.0.7 on 2026-01-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_type_spending_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='saved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
