# Generated by Django 5.0.7 on 2026-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_goal_saved_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='color',
            field=models.TextField(default='#10b981'),
        ),
        migrations.AddField(
            model_name='budget',
            name='icon',
            field=models.TextField(default='cash-outline'),
        ),
        migrations.AddField(
            model_name='goal',
            name='color',
            field=models.TextField(default='#10b981'),
        ),
        migrations.AddField(
            model_name='goal',
            name='icon',
            field=models.TextField(default='flag-outline'),
        ),
    ]
