# Generated by Django 5.0.7 on 2026-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_budget_color_budget_icon_goal_color_goal_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
