# Generated by Django 5.0.7 on 2026-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_goal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.TextField(choices=[('REGULAR', 'Regular'), ('SAVINGS', 'Savings')], default='REGULAR'),
        ),
    ]
