# Generated by Django 5.0.7 on 2026-01-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
