# Generated by Django 5.0.7 on 2026-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_transaction_time_income_next_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.TextField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit')], default='EXPENSE'),
        ),
    ]
