# Generated by Django 5.2.7 on 2025-10-17 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query', models.TextField()),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_data', models.JSONField(default=dict)),
                ('database_results', models.JSONField(default=dict)),
                ('explanations', models.JSONField(default=dict)),
                ('analysis_output', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True, null=True)),
                ('insights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='personal_assistant_api.analysisrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['request_id'], name='personal_a_request_6323c6_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['status'], name='personal_a_status_65a724_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['-created_at'], name='personal_a_created_34c4ba_idx'),
        ),
    ]
