# Generated by Django 5.0.7 on 2026-01-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('birthday', models.DateField()),
                ('gender', models.TextField(blank=True, choices=[('1', 'male'), ('2', 'female')], null=True)),
                ('employment_status', models.TextField(blank=True, choices=[('1', 'Employed Full-time'), ('2', 'Employed Part-time'), ('3', 'Unemployed'), ('4', 'Retired')], null=True)),
                ('education_level', models.TextField(blank=True, choices=[('1', 'High school'), ('2', 'Associate degree'), ('3', 'Bachelor degree'), ('4', 'Masters Degree'), ('5', 'PhD')], null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_persona', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
