# Generated by Django 5.2.7 on 2025-10-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_assistant_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysisrequest',
            new_name='personal_as_request_40e363_idx',
            old_name='personal_a_request_6323c6_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisrequest',
            new_name='personal_as_status_c2a06e_idx',
            old_name='personal_a_status_65a724_idx',
        ),
        migrations.RenameIndex(
            model_name='analysisrequest',
            new_name='personal_as_created_7474c4_idx',
            old_name='personal_a_created_34c4ba_idx',
        ),
    ]
